# Generated by Django 5.0.6 on 2024-07-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wedding', '0002_vendor_user_wedding_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='select',
            name='status',
            field=models.TextField(default='pending'),
        ),
    ]
