# Generated by Django 3.2.25 on 2024-09-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wedding', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=1, max_length=29),
            preserve_default=False,
        ),
    ]
